# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{captured}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher Sexton"]
  s.date = %q{2010-05-18}
  s.default_executable = %q{captured}
  s.description = %q{Because <shift>-<command>-4 is the single most useful shorcut in Macdom}
  s.email = %q{csexton@gmail.com}
  s.executables = ["captured"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "README.markdown",
     "VERSION",
     "bin/captured",
     "etc/captured.yml-example",
     "etc/launchd.plist.erb",
     "lib/captured.rb",
     "lib/captured/file_tracker.rb",
     "lib/captured/file_uploader.rb",
     "lib/captured/fs_events.rb",
     "lib/captured/history.rb",
     "lib/captured/uploaders/eval_uploader.rb",
     "lib/captured/uploaders/imageshack_uploader.rb",
     "lib/captured/uploaders/imgur_uploader.rb",
     "lib/captured/uploaders/scp_uploader.rb",
     "resources/2uparrow.png",
     "resources/action_run.png",
     "resources/captured-box.png",
     "resources/captured-empty-box.png",
     "resources/captured.png",
     "resources/green_check.png",
     "resources/growlnotify",
     "resources/red_star.png",
     "resources/red_x.png",
     "resources/ruby.png",
     "spec/bin/mockgrowlnotify",
     "spec/captured_spec.rb",
     "spec/file_uploader_spec.rb",
     "spec/fixtures/history",
     "spec/fixtures/scp_config.yml",
     "spec/history_spec.rb",
     "spec/spec_helper.rb",
     "spec/uploader_specs/imageshack_uploader_spec.rb",
     "spec/uploader_specs/imgur_uploader_spec.rb",
     "spec/uploader_specs/scp_uploader_spec.rb"
  ]
  s.homepage = %q{http://github.com/csexton/captured}
  s.post_install_message = %q{
   =========================================================================

             Thanks for installing Captured! You can now run:

   captured --install      to setup launchd to run captured in the background

    When you install an example config file to ~/.captured.yml, which has a
    few examples of possible configuration types.

   =========================================================================

}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{captured}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Quick screenshot sharing for OS X}
  s.test_files = [
    "spec/captured_spec.rb",
     "spec/file_uploader_spec.rb",
     "spec/history_spec.rb",
     "spec/spec_helper.rb",
     "spec/uploader_specs/imageshack_uploader_spec.rb",
     "spec/uploader_specs/imgur_uploader_spec.rb",
     "spec/uploader_specs/scp_uploader_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<imgur>, [">= 0"])
      s.add_runtime_dependency(%q<net-scp>, [">= 0"])
    else
      s.add_dependency(%q<imgur>, [">= 0"])
      s.add_dependency(%q<net-scp>, [">= 0"])
    end
  else
    s.add_dependency(%q<imgur>, [">= 0"])
    s.add_dependency(%q<net-scp>, [">= 0"])
  end
end

